.TH "Dokumentacja katalogu src/" 3 "Cz, 23 maj 2013" "Version 0.1" "Life -- Fight!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dokumentacja katalogu src/ \- 
.SH SYNOPSIS
.br
.PP
.SS "Katalogi"

.in +1c
.ti -1c
.RI "katalog \fBclient\fP"
.br
.ti -1c
.RI "katalog \fBcommon\fP"
.br
.ti -1c
.RI "katalog \fBinit\fP"
.br
.ti -1c
.RI "katalog \fBserver\fP"
.br
.in -1c
.SS "Pliki"

.in +1c
.ti -1c
.RI "plik \fBmain\&.cpp\fP"
.br
.in -1c
