.TH "As" 3 "Mon Mar 11 2013" "Version 0.1" "Life -- Fight!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
As \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtestMeToo\fP (char c1, char c2)"
.br
.RI "\fIA pure virtual member\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void As::testMeToo (charc1, charc2)\fC [virtual]\fP"

.PP
A pure virtual member\&. \fBSee Also:\fP
.RS 4
\fBtestMe()\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIc1\fP the first argument\&. 
.br
\fIc2\fP the second argument\&. 
.RE
.PP

.PP
Implements \fBTest\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Life -- Fight! from the source code\&.
