.TH "Config" 3 "Cz, 23 maj 2013" "Version 0.1" "Life -- Fight!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config \- 
.PP
Klasa przechowujaca komplet ustawien wybranych przez uzytkownika na ekranie startowym\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Config\&.hpp>\fP
.SS "Atrybuty publiczne"

.in +1c
.ti -1c
.RI "int \fBmap_width\fP"
.br
.ti -1c
.RI "int \fBmap_height\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa przechowujaca komplet ustawien wybranych przez uzytkownika na ekranie startowym\&. 

\fBDo zrobienia\fP
.RS 4
moze zrobmy z tego singleton? 
.RE
.PP

.SH "Dokumentacja atrybutów składowych"
.PP 
.SS "int Config::map_height"

.SS "int Config::map_width"


.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Life -- Fight!\&.
