.TH "Herbivore" 3 "Cz, 23 maj 2013" "Version 0.1" "Life -- Fight!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Herbivore \- 
.PP
Klasa reprezentujaca roslinozerce\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Herbivore\&.hpp>\fP
.PP
Dziedziczy \fBCreature\fP\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBHerbivore\fP (double x_pos, double y_pos)"
.br
.RI "\fIKonstruktor wywoływany w przypadku, gdy stworzenie jest generowane na początku gry\&. \fP"
.ti -1c
.RI "virtual void \fBsimulationStep\fP (int miliseconds)"
.br
.RI "\fIFunkcja wykonuje jeden krok symulacji dla obiektu\&. \fP"
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.RI "\fISerializacja\&. \fP"
.in -1c
.SS "Dodatkowe Dziedziczone Składowe"
.SH "Opis szczegółowy"
.PP 
Klasa reprezentujaca roslinozerce\&. 

\fBDo zrobienia\fP
.RS 4
write me 
.RE
.PP

.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "Herbivore::Herbivore (doublex_pos, doubley_pos)\fC [inline]\fP"

.PP
Konstruktor wywoływany w przypadku, gdy stworzenie jest generowane na początku gry\&. Wspolrzedne stworzenia są podawane jako parametry konstruktora\&.
.PP
Stworzenie pojawi się w wybranym miejscu na planszy (powinno ono byc wolne)\&. 
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "template<class Archive > void Herbivore::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP"

.PP
Serializacja\&. \fBZobacz również:\fP
.RS 4
\fBMap::serialize\fP 
.RE
.PP

.PP
Reimplementowana z \fBCreature\fP\&.
.SS "virtual void Herbivore::simulationStep (intmiliseconds)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Funkcja wykonuje jeden krok symulacji dla obiektu\&. Poszczególne elementy symulacji (poszukiwanie pożywienia, poszukiwanie wody, polowanie, ucieczka, poszukiwanie schronienia, poszukiwanie partnera do reprodukcji) są wywoływane w odpowiedniej kolejności, wg piramidy potrzeb osobnika\&.
.PP
\fBParametry:\fP
.RS 4
\fImiliseconds\fP czas w milisekundach, który upłynął od poprzedniego kroku 
.RE
.PP

.PP
Implementuje \fBCreature\fP\&.

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Life -- Fight!\&.
