.TH "Map" 3 "Cz, 23 maj 2013" "Version 0.1" "Life -- Fight!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Map \- 
.PP
Klasa reprezentujaca mape (obszar gry) wraz z zawartymi na niej obiektami\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Map\&.hpp>\fP
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBMap\fP (int width, int height)"
.br
.RI "\fIKonstruktor tworzacy pusta mape o zadanych wymiarach\&. \fP"
.ti -1c
.RI "void \fBcreateSomeRandomObjects\fP ()"
.br
.RI "\fITYMCZASOWA FUNKCJA DO TESTOWANIA\&. \fP"
.ti -1c
.RI "int \fBcountObjects\fP ()"
.br
.RI "\fITYMCZASOWA FUNKCJA DO TESTOWANIA\&. \fP"
.ti -1c
.RI "void \fBsimulationStep\fP (int miliseconds)"
.br
.RI "\fIPrzeprowadza jeden krok symulacji dla wszystkich obiektow na mapie\&. \fP"
.in -1c
.SS "Metody chronione"

.in +1c
.ti -1c
.RI "template<class Archive > void \fBserialize\fP (Archive &ar, const unsigned int version)"
.br
.RI "\fISerializacja (np na potrzeby zapisu/odczytu map na dysku) \fP"
.in -1c
.SS "Atrybuty chronione"

.in +1c
.ti -1c
.RI "std::vector< \fBMapObject\fP * > \fBobjects\fP"
.br
.RI "\fIWektor zawierający wszystkie obiekty znajdujące się na mapie\&. \fP"
.ti -1c
.RI "const int \fBwidth_\fP"
.br
.ti -1c
.RI "const int \fBheight_\fP"
.br
.in -1c
.SS "Przyjaciele"

.in +1c
.ti -1c
.RI "class \fBboost::serialization::access\fP"
.br
.in -1c
.SH "Opis szczegółowy"
.PP 
Klasa reprezentujaca mape (obszar gry) wraz z zawartymi na niej obiektami\&. 

Klasa może być serializowana przy pomocy boost::serialize
.PP
\fBDo zrobienia\fP
.RS 4
write me 
.RE
.PP

.SH "Dokumentacja funkcji składowych"
.PP 
.SS "int Map::countObjects ()\fC [inline]\fP"

.PP
TYMCZASOWA FUNKCJA DO TESTOWANIA\&. \fBDo zrobienia\fP
.RS 4
USUN MNIE GDY NAPISZESZ BARDZIEJ ZAAWANSOWANE TESTY!!! 
.RE
.PP

.SS "void Map::createSomeRandomObjects ()\fC [inline]\fP"

.PP
TYMCZASOWA FUNKCJA DO TESTOWANIA\&. \fBDo zrobienia\fP
.RS 4
USUN MNIE GDY NAPISZESZ BARDZIEJ ZAAWANSOWANE TESTY!!! 
.RE
.PP

.SS "template<class Archive > void Map::serialize (Archive &ar, const unsigned intversion)\fC [inline]\fP, \fC [protected]\fP"

.PP
Serializacja (np na potrzeby zapisu/odczytu map na dysku) Do serializacji uzywamy boost::serialize\&. Aby prawidlowo serializowac klasy dziedziczace po \fBMapObject\fP, nalezy uzyc makra BOOST_CLASS_EXPORT w pliku cpp, w ktorym beda wolane metody serializacji\&.
.PP
Wiecej informacji: http://stackoverflow.com/questions/3396330/where-to-put-boost-class-export-for-boostserialization
.PP
Obecnie metoda nie jest uzywana
.PP
\fBDo zrobienia\fP
.RS 4
uzyj mnie! 
.RE
.PP

.SS "void Map::simulationStep (intmiliseconds)\fC [inline]\fP"

.PP
Przeprowadza jeden krok symulacji dla wszystkich obiektow na mapie\&. \fBParametry:\fP
.RS 4
\fImiliseconds\fP czas w milisekundach, który upłynął od poprzedniego kroku 
.RE
.PP

.SH "Dokumentacja atrybutów składowych"
.PP 
.SS "std::vector<\fBMapObject\fP *> Map::objects\fC [protected]\fP"

.PP
Wektor zawierający wszystkie obiekty znajdujące się na mapie\&. Rozróżnienie typów obiektów zagwarantują wirtualne metody w hierarchii klas dziedziczących po typie \fBMapObject\fP\&.
.PP
\fBDo zrobienia\fP
.RS 4
zmienic strukture danych na cos lepszego (moze mapa?) 
.RE
.PP


.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Life -- Fight!\&.
