.TH "md_GENETYKA" 3 "Cz, 23 maj 2013" "Version 0.1" "Life -- Fight!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_GENETYKA \- DNA: linie papilarne 
Witam w pierwszym wpisie z serii 'DNA'\&. Poświęcę go liniom papilarnym\&. Pierwsze pytanie to czym one są\&. Dobra, widzimy jakieś wzorki, jednak nie jest to specjalnie dobre wyjaśnienie\&. Inna nazwa lini papilarnych to linie brodawkowe\&. Ta nazwa mówi już coś więcej\&. Jeszcze dokładniej można o nich powiedzieć, że są to wytwory skóry właściwej, bruzdy do których wnikają zakończenia nerwów\&. Mają je tylko ssaki naczelne i misie Koala\&.
.PP
Jak zapewne wiecie, dla każdego z nas są one niepowtarzalne\&. Nie ma możliwości by były dwie osoby z identycznym układem linii\&. Oczywiście taką właściwość człowiek wykorzystał\&. Zauważył ją w XIX wieku, jednak dopiero w latach 30\&. XX wieku zaczął ją wykorzystywać\&. Obecnie odciski palców są powszechnie używane przez policję i inne organizacje dbające o bezpieczeństwo\&. Dzięki nim (nierozważni) przestępcy mogą zacząć oglądać niebo w kratkę\&. Do zidentyfikowania sprawcy używa się tzw\&. minucji - charakterystycznych cech jak np\&. rozwidleń, zagięć, haczyków itp\&. By mieć praktycznie 100% pewność wystarczy już 12 identycznych minucji, jednak może wystarczyć mniej - zależy to od ich rzadkości\&. Tyle też wystarczy by uznać odcisk za wiarygodny w świetle polskiego prawa\&. Aha\&. Nauka zajmująca się tymi sprawami to daktyloskopia\&.
.PP
Czasami można usłyszeć o zasadzie 3N Francisa Galtona\&. Mówi ona że linie są niepowtarzalne, niezmienne i nieusuwalne\&. O ile do pierwszych dwóch stwierdzeń nie można się przyczepić, to 'nieusuwalne' nie jest już dobrym określeniem\&. W dzisiejszych czasach jeżeli tylko chcesz możesz się ich pozbyć\&. Oczywiście wiąże się to z zabiegiem dermatologicznym\&. Niestety zdarzają się sytuacje w których to natura podejmuje za nas decyzje\&. Dwie, bardzo rzadkie, choroby genetyczne wywołują brak linii papilarnych\&. Jest to spowodowane uszkodzeniem białka keratyna 14\&.
.PP
Na początku napisałem że wszyscy mają różne linie\&. Tutaj chciałbym wspomnieć, że nawet bliźnięta nie są wyjątkami\&. Mimo że mają takie samo DNA, ich linie papilarne są różne\&. Jednak o kwasie dezoksyrybonukleinowym napiszę za niedługo\&.
.PP
To tyle jeśli chodzi o linie papilarne\&. Zapraszam do następnego wpisu z serii 'DNA'\&. Napiszę w nim o cechach dziedzicznych u człowieka - już niebawem\&.
.PP
.SH "DNA: cechy dziedziczne"
.PP
.PP
Witam w drugim wpisie z serii 'DNA'\&. Dziś napiszę o cechach dziedzicznych u człowieka\&. Jeżeli ktoś uważnie ogląda Dr\&. House'a, to w jednym odcinku chłopak stwierdził, że wie iż jest adoptowany już od 5 klasy - znalazł w internecie informację, że podbródek który on ma, jest cechą dziedziczną, a żaden z jego przybranych rodziców go nie miał\&. Oczywiście nie chodzi mi tu abyśmy wszyscy zaczęli porównywać swoje cechy wyglądu z rodzicami\&. Powiedzmy że to co tutaj napiszę jest swoistą ciekawostką\&. Na dodatek niektóre cechy można odziedziczyć po przodkach (babci, dziadku, prababci)\&.
.PP
Przejdźmy do konkretów\&. Dziedziczymy cechy fizyczne i psychiczne oraz biohemiczne\&. W psychicznych zawierają się m\&.in\&. podatności na pewne czynniki zewnętrzne\&. W fizycznych i biochemicznych dziedziczymy wygląd oraz cechy "wewnętrne (m\&.in\&. grupę krwi)\&. Oto niektóre cechy dziedziczne:
.PP
.IP "\(bu" 2
kolor oczu
.IP "\(bu" 2
kształt i wielkość oczu
.IP "\(bu" 2
ułożenie oczu
.IP "\(bu" 2
długość rzęs ( długie 'dominują' nad krótkimi )
.IP "\(bu" 2
kształt uszu
.IP "\(bu" 2
kolor włosów
.IP "\(bu" 2
grupy krwi
.IP "\(bu" 2
czynnik Rh
.IP "\(bu" 2
inteligencja ( dziedziczna genowo i w dużym stopniu uwarunkowana czynnikami zewnętrznymi,środowiska )
.IP "\(bu" 2
leworęczność i praworęczność
.IP "\(bu" 2
umiejętność zwijania języka
.IP "\(bu" 2
sposób ułożenia dłoni 'do pacierza' ( chodzi o to czy kciuk lewej ręki leży pod kciukiem prawej ręki czy na odwrót) Niestety dziedziczne są też choroby genetyczne\&.
.PP
.PP
W tym temacie warto wspomnieć o eugenice\&. Jest to nauka zajmująca się sterowaniem genami\&. Chodzi o to by stworzyć jak najlepszy organizm poprzez krzyżowanie osobników z porządanymi cechami\&. W ten sposób można otrzymać coraz to 'lepszy' osobnik danego gatunku\&. Jeżeli chcecie to możecie zrobić taki eksperyment w domu\&. Wystarczy że macie akwarium i gupiki\&. Przyjmujemy że mamy kilka samców\&. Chodzi nam by uzyskać samca z jak największym (i najpiękniejszym) ogonem\&. Wystarczy go skrzyżować z samicą gupika, a następnie z potomstwa wybrać kolejnego samca z największym ogonem i tak dalej\&.
.PP
DNA: gust i indywidualizm
.PP
Podobno o gustach się nie rozmawia\&. Jednak czym on jest? Dodatkowo indywidualność\&. Dlaczego jesteśmy tacy jacy jesteśmy?
.PP
Gdy mówimy że ktoś ma dobry gust, chodzi nam jego wybory w kwestii estetycznej\&. Mówimy że ktoś urządził swoje mieszkanie gustownie - czyli estetycznie i ze smakiem\&. Nie jest to cecha z którą się rodzimy, nie dziedziczymy jej\&. Gust musi zostać nam wpojony\&. Oczywiście wiele zależy od środowiska w którym żyje człowiek\&. Gustem można nazwać ocenianie wyżej pewnych wartości, a niżej innych\&. Oczywiście jest to poniekąd sprawa podświadoma i często polega na tym że wg\&. nas 'coś pasuje, a coś nie'\&.
.PP
Drugi temat to indywidualność\&. Nasz własny styl\&. Podobnie jak gust, nie rodzimy się z nim\&. Kształtujemy go sobie sami\&. Duży udział w jego kształtowaniu ma środowisko w którym żyjemy, jego poglądy i sposób życia\&. Oczywiście indywidualność to także nasz stosunek do otoczenia\&. To czy jesteśmy 'dowódcami', czy może 'robotnikami'\&. Jak odnajdujemy się i zachowujemy w naszym środowisku\&. Czy potrafimy mieć własne zdanie czy może idziemy razem z tłumem\&.
.PP
DNA: stres
.PP
Jak wiemy stres jest w naszym życiu obecny bez przerwy\&. Rano, kiedy idziemy do szkoły, podczas nauki, popołudniu kiedy gonią nas terminy, wieczorem kiedy to odrabiamy zadania domowe\&. Oczywiście istnieje świat bez szkoły, ale i on nie jest wolny od stresu - praca, brak pracy (bezrobocie), obowiązki domowe itd\&. itp\&.
.PP
Jednakże czym on jest\&. Można powiedzieć że stres, jest to nasza (naszego organizmu) reakcja na czynniki zewnętrzne\&. Oczywiście czynniki te są w naszym odczuciu negatywne i przynoszą nieporządane skutki\&.
.PP
Oczywiście stres ma także pozytywne aspekty\&. Niekiedy potrafi motywować\&. Jednakże gdy jest on zbyt duży powoduje biegunowo odmienne zachowanie\&. Gdy jest on przewlekły (np\&. bardzo stresująca praca) może doprowadzić do różnego rodzaju schorzeń jak np\&. nerwica, lub odpowiedzi fizycznej organizmu (bóle, wzrost ciśnienia itd\&.)\&.
.PP
Oczywiście stres można próbować opanować\&. Nie będę pisał jak, gdyż nie jestem jakimś specjalistą w tej dziedzinie\&. Jednak ważne jest uzmysłowienie sobie że mamy nad nim kontrolę\&. Niektórzy ludzie uważają że stres jest już odrębnym bytem będącym nieodłączną częścią ich życia\&. To nie jest dobre\&. Ludzie tacy obwiniają za taki stan rzeczy swoją osobowość, czynniki zewnętrzne jak np\&. pracę, znajomego, sytuację życiową\&. Mimo że może się wydawać że jest to jakaś metoda, nie jest to dobre\&. Ciągłe życie w stresie, jak pisałem na początku, jest niezdrowe, a umiejętność radzenia sobie z nim jest bardzo ważna\&.
.PP
Oczywiścią są pewne uwarunkowania dzięki którym jedni lepiej radzą sobie ze stresem, a inni gorzej\&. Zależy to, w głównej mierze, od środowiska w jakim żyjemy, ale także po trochu od genów\&.
.PP
Był to ostatni wpis z serii 'DNA'\&. Dzięki wszystkim którzy to czytali\&. Piszcie opinie jak wam się podobała ta seria\&. 
