.TH "md_TLUMACZENIA" 3 "Cz, 23 maj 2013" "Version 0.1" "Life -- Fight!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_TLUMACZENIA \- TLUMACZENIA 
Lista oficjalnych tłumaczeń terminów używanych w grze:
.PP
.IP "\(bu" 2
Zwierzę, stworzenie - creature
.IP "\(bu" 2
Plansza, mapa - map
.IP "\(bu" 2
Wodopój - waterhole
.IP "\(bu" 2
Drzewo - tree
.IP "\(bu" 2
Drapieżnik - predator
.IP "\(bu" 2
Roślinożerca - herbivore
.IP "\(bu" 2
Jasnika - lair 
.PP

