.TH "todo" 3 "Cz, 23 maj 2013" "Version 0.1" "Life -- Fight!" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Lista rzeczy do zrobienia 
.IP "\fBKlasa \fBcommon::Config\fP \fP" 1c
moze zrobmy z tego singleton?  
.IP "\fBSkładowa \fBcommon::Creature::Creature\fP (const Creature &mother, const Creature &father)\fP" 1c
write me  
.IP "\fBSkładowa \fBcommon::Creature::Creature\fP (double x_pos, double y_pos)\fP" 1c
write me  
.IP "\fBSkładowa \fBcommon::Creature::isDead\fP () const \fP" 1c
write me  
.IP "\fBKlasa \fBcommon::Herbivore\fP \fP" 1c
write me  
.IP "\fBKlasa \fBcommon::Map\fP \fP" 1c
write me  
.IP "\fBSkładowa \fBcommon::Map::objects\fP \fP" 1c
zmienic strukture danych na cos lepszego (moze mapa?)  
.IP "\fBSkładowa \fBcommon::Map::serialize\fP (Archive &ar, const unsigned int version)\fP" 1c
uzyj mnie! 
.PP

