
## JESTEM TYMCZASOWYM MAKEFILEM
## JESLI MOZESZ, ZAMIEN MNIE NA COS LEPSZEGI
## NA PRZYKLAD PLIK SCONS


all:
	g++ main.cpp init/*.cpp client/*.cpp server/*.cpp common/*.cpp -g -std=c++11 -lqt -lboost_thread -lboost_serialization -o ../bin/life

run:
	./../bin/life
